- name: Load a variable file based on the OS type
  include_vars: "{{ item }}"
  with_first_found:
  - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "vars/{{ ansible_distribution }}.yml"
  - "vars/{{ ansible_os_family }}.yml"
  - "vars/defaults.yml"

- name: "OS dependant"
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"

- name: "Install nvim"
  include_tasks: "../scripts/install_nvim.yml"
  
- name: "Install Go"
  include_tasks: "../scripts/install_go.yml"

- name: Configure Gitlab SSH Key
  ansible.builtin.command: pwsh -f ./scripts/configure-ssh.ps1 '{{ lookup('ansible.builtin.env', 'GITLAB_TOKEN') }}'
