- name: "Install apt"
  include_tasks: "../scripts/install_apt.yml"

- name: "Install flatpak"
  include_tasks: "../scripts/install_flatpak.yml"

- name: "Install fonts"
  include_tasks: "../scripts/install_fonts.yml"

- name: Enable wayland 
  shell: sed -i 's/WaylandEnable=false/WaylandEnable=true/' /etc/gdm3/custom.conf

- name: Start and enable services
  ansible.builtin.systemd:
    state: started
    name: "{{ item }}"  
    enabled: yes 
  with_items:  "{{ services_to_enable }}"     

- name: Add user to groups
  ansible.builtin.user:
    name: user
    groups: "{{ item }}"  
    append: yes    
  with_items:  "{{ groups_to_add }}"       

