- name: copy wallpaper file
  copy:
    src: files/wallpaper.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: set gnome config
  become_user: user
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:  "{{ dconf }}"      
