- name: Load a variable file based on the OS type
  include_vars: "{{ item }}"
  with_first_found:
  - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "vars/{{ ansible_os_family }}.yml"
  - "vars/defaults.yml"

- name:
  #include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  include_tasks: "defaults.yml"
