---
nvim_version: v0.9.1
go_verison: go1.20.5
s76keyboard_version: 1.3.7
fonts: 
    - {url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraMono.zip, name: 'Fira*Mono*'}
    - {url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Go-Mono.zip, name: 'GoMonoNerdFont-*'}
    - {url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip, name: 'Fira*Code*'}
