dconf:
    - {key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding', value: "'<Super>t'"}
    - {key: '/org/gnome/desktop/datetime/automatic-timezone', value: "true"}
    - {key: '/org/gnome/desktop/interface/clock-show-date', value: "true"}
    - {key: '/org/gnome/desktop/interface/clock-format', value: "'12h'"}
    - {key: '/org/gnome/desktop/background/picture-uri', value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"}
    - {key: '/org/gnome/desktop/interface/color-scheme', value: "'prefer-dark'"}
    - {key: '/org/gnome/desktop/interface/document-font-value', value: "'FiraCode Nerd Font weight=450 11'"}
    - {key: '/org/gnome/desktop/interface/monospace-font-value', value: "'FiraCode Nerd Font Mono weight=450 10'"}
    - {key: '/org/gnome/desktop/interface/font-value', value: "'FiraCode Nerd Font weight=450 11'"}
    - {key: '/org/gnome/desktop/wm/preferences', value: "'FiraCode Nerd Font weight=450 11'"}
    - {key: '/org/gnome/desktop/sound', value: "true"}
    - {key: '/org/gnome/shell/favorite-apps', value: "['firefox.desktop','terminator.desktop']"}
    - {key: '/org/gnome/shell/enabled-extensions', value: "['pop-shell@system76.com','dash-to-dock@micxgx.gmail.com']"}
    - {key: '/org/gnome/extensions/pop-shell/tile-by-default', value: "true"}
    - {key: '/org/gnome/extensions/pop-shell/gap-innger', value: "uint32 1"}
    - {key: '/org/gnome/extensions/pop-shell/gap-outer', value: "uint32 1"}
    - {key: '/org/gnome/extensions/dash-to-dock/dash-max-icon', value: "32"}
