- name: download Nvim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage"
    dest: /usr/bin/nvim
    mode: '0755'
    checksum: sha256:https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage.sha256sum

- name: check if nvchad is installed
  become_user: user
  stat: 
    path: ~/.config/nvim 
  register: nvchad

- name: Download NVChad
  become_user: user
  shell: git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 
  when: nvchad.stat.exists == false
