- name: download Nvim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage"
    dest: /usr/bin/nvim
    mode: '0755'
    checksum: sha256:https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage.sha256sum
